export const elements = Object.freeze({
  saleImage: `#sale_image`,
  searchInput: `#search_product`,
  submitSearchButton: `#submit_search`,
  womenAccordionExpandButton: `//*[@id='accordian']//a[@href="#Women"]`,
  menAccordionExpandButton: `//*[@id='accordian']//a[@href="#Men"]`,
  kidsAccordionExpandButton: `//*[@id='accordian']//a[@href="#Kids"]`,
  womenSectionDressButton: `//*[@id='Women']//a[text()='Dress ']`,
  womenSectionTopsButton: `//*[@id='Women']//a[text()='Tops ']`,
  womenSectionSareeButton: `//*[@id='Women']//a[text()='Saree ']`,
  menSectionTShirtButton: `//*[@id='Men']//*[text()='Tshirts ']`,
  menSectionJeansButton: `//*[@id='Men']//*[text()='Jeans ']`,
  kidsSectionBabyDressButton: `//*[@id='Kids']//*[text()='Dress ']`,
  kidsSectionBabyTShirtButton: `//*[@id='Kids']//*[text()='Tops & Shirts ']`,
});
